name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        theme:
          - bootstrap
          - educorvi
          - siguv
          - guvh
          - bghw
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v3
      - run: npm ci
      - name: Build ${{matrix.theme}}
        run: ./createDist.js ${{matrix.theme}}
      - name: Copy zip into dist folder
        run: cp dist.zip dist/${{matrix.theme}}.zip
      - uses: actions/upload-artifact@v4
        with:
          name: ${{matrix.theme}}
          path: dist/*
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Get the current tag
        id: get_tag
        run: echo "::set-output name=tag::$(git describe --tags --exact-match || echo '')"

      - name: Determine if it's a prerelease
        id: prerelease_check
        run: |
          if [[ "${{ steps.get_tag.outputs.tag }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+-pre\.[0-9]+$ ]]; then
            echo "pre-release=true" >> $GITHUB_ENV
          else
            echo "pre-release=false" >> $GITHUB_ENV
          fi
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*/*.zip
          prerelease: ${{ env.pre-release }}

