name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        theme:
          - bootstrap
          - educorvi
          - siguv
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-node@v3
      - run: npm ci
      - name: Build ${{matrix.theme}}
        run: ./createDist.js ${{matrix.theme}}
      - name: Copy zip into dist folder
        run: cp dist.zip dist/${{matrix.theme}}.zip
      - uses: actions/upload-artifact@v3
        with:
          name: ${{matrix.theme}}
          path: dist/*
  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/*/*.zip

